const HAMBURGUESAS = [
    {
        id:1,
        name:"Stop & Play",
        price:560,
        detail: "Cheddar - cebolla  crocante - mayonesa secreta - bacon",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=1COuk7isEJQxNt1_yyyo2JwGXyt91L6EX',
        codigo:"/stopnplay",
        stock:13,
    },
    {
        id:2,
        name:"Fly High",
        price:700,
        detail:"Doble Cheddar - doble emmental",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=1pYDpMjF4smkgDXhsWlRWLvBQLbgul3oq',
        codigo:"/flyhigh",
        stock:12,
    },
    {
        id:3,
        name:"Underground Love",
        price:550,
        detail:"Cheddar - bacon - salsa magumbo",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=1am3tk9SZVfZsVIEHQ6YCJkD6XnOFnqlK',
        codigo:"/undergroundlove",
        stock:11,
    },
    {
        id:4,
        name:"On the Edge",
        price:450,
        detail:"Cheddar - bacon - salsa magumbo",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=1laXknvwmHqI1ZgYsI1IqDlKXciri_dDE',
        codigo:"/ontheedge",
        stock:5,
    },
    {
        id:5,
        name:"Phantom Thief",
        price:590,
        detail:"Cheddar - bacon - salsa magumbo",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=19IGBiNTJVJzBbloGoXOAT7rjaV1w9Qcx',
        codigo:"/phantomthief",
        stock:2,
    },
    {
        id:6,
        name:"Bridges",
        price:670,
        detail:"Cheddar - bacon - salsa magumbo",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=15vbIz9vKIxPx8VmnWVR7YLD6JaJGDacB',
        codigo:"/bridges",
        stock:1,
    },
    {
        id:7,
        name:"Panzer Grove",
        price:750,
        detail:"Cheddar - bacon - salsa magumbo",
        pictureUrl:'https://drive.google.com/uc?/export=view&id=1hweoSrhfKh9nMGlD1Xd2YWBxGng3i4Kj',
        codigo:"/panzergrove",
        stock:22,
    }];

    export default HAMBURGUESAS